Feature/molvis refactoring
inviwo/modules pull request #142
Opened 2020-12-22 17:12 UTC by martinfalk

* refactored molecular rendering into two options
  1. direct rendering of a `MolecularStructure` using a `Molecular Renderer` processor
  2. indirect rendering of a molecular mesh with `Molecular Mesh Renderer`
* added picking/tooltips for atoms
* utility functions for amino acids and chains
* different commonly-used colormaps (atoms & residues)
* regression tests and example pdb files

2021-01-04 13:24 UTC, petersteneteg requested changes

2021-01-04 13:24 UTC, petersteneteg commented on molvis/molvisbase/src/io/basicpdbreader.cpp
> +            }
could extract this into function
```
template <typename T>
T parseSection(string_view line, size_t begin, size_t size, sting_view tag, string_view desc) {
    T res;
    if (!detail::fromStr(line.substr(start, size), res)) {
        parseException(tag, desc);
    }
    return res;
}
```
then you could just write 
```
const auto occupancy = parseSection<double>(line, 54, 6, tag, "invalid occupancy");
const auto Bfactor = parseSection<double>(line, 60, 6, tag, "invalid temperature factor");
```
etc...

2021-01-04 13:24 UTC, petersteneteg commented on molvis/molvisbase/src/io/basicpdbreader.cpp
> +            data.atoms.fullNames.push_back(std::string(fullName));
emplace_back, then you don't need the std::string

2021-01-04 13:24 UTC, petersteneteg commented on molvis/molvisgl/src/processors/molecularrenderer.cpp
> +        auto mesh = createMesh(*structure);
is this something you want to do every frame? seems expensive

2021-02-10 15:02 UTC, martinfalk commented on molvis/molvisbase/include/inviwo/molvisbase/util/aminoacid.h
> +    Xle,
that is allowed according to the standard :)

2021-02-11 10:50 UTC, martinfalk commented on molvis/molvisbase/src/io/basicpdbreader.cpp
> +    addExtension(FileExtension("pdb", "Protein Databank files (pdb)"));
no, that should be fine I think. Needs testing though.

2021-02-11 10:50 UTC, martinfalk commented on molvis/molvisbase/src/util/utilities.cpp
> +constexpr vec3 hsvToRgb(vec3 c) noexcept {
removed.

2021-02-11 10:51 UTC, martinfalk commented on molvis/molvisbase/src/util/utilities.cpp
> +    constexpr float hclmaxL = 0.530454533953517f;  // == exp(hclgamma / hcly0) - 0.5
`exp` not being constexpr

2021-02-11 13:25 UTC, petersteneteg approved these changes

2021-02-12 08:41 UTC, petersteneteg approved these changes

2021-02-12 08:41 UTC, merged