netcdf: Fix python error
inviwo/modules pull request #155
Opened 2021-03-15 18:52 UTC by ResearchDaniel

Error(s) occur when using the following setup:
Anaconda 3, Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

Error reloading file: C:/inviwo/modules/misc/netcdf/python/processors/netcdfvolumesource.py Message:
Failed to load processor NetCDFVolumeSource from script: C:/inviwo/modules/misc/netcdf/python/processors/netcdfvolumesource.py.
TypeError: 'type' object is not subscriptable

At:
  C:/inviwo/modules/misc/netcdf/python\genericnetcdfsource.py(66): GenericNetCDFSource
  C:/inviwo/modules/misc/netcdf/python\genericnetcdfsource.py(11): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(783): exec_module
  <frozen importlib._bootstrap>(609): _exec
  C:\Users\danjo\Anaconda3\Lib\importlib\__init__.py(176): reload
  <string>(11): <module>

2021-03-15 18:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inviwo/modules?pullRequest=155) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/inviwo/modules?pullRequest=155) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inviwo/modules?pullRequest=155) it.</sub>

2021-03-16 15:00 UTC, AnkeAnke commented
I'm not that well versed in python and have never used parameter types before (those were added by Peter). Would be good if @petersteneteg can quickly check it.

2021-03-16 19:07 UTC, petersteneteg requested changes
That fix is wrong. I think you might need to use the typing module for list pre python 3.9 but I don't remember from the top of my head. Just use the latest python...

2021-03-17 18:38 UTC, ResearchDaniel commented
Ok, added a requirement on Python 3.9. Also added an explanation on how to avoid using 3.9 in case one cannot upgrade in the commit log.

2021-03-17 20:24 UTC, petersteneteg approved these changes

2021-03-18 08:16 UTC, martinfalk commented
> Ok, added a requirement on Python 3.9. Also added an explanation on how to avoid using 3.9 in case one cannot upgrade in the commit log.

So, we have a fix for Python <3.9, why not just use that one then instead of enforcing 3.9?

2021-03-18 08:52 UTC, ResearchDaniel commented
@martinfalk That would require installing an additional package in Python and still only works for >= 3.6. So there is a little bit of a trade-off. I think we can leave potential adjustments to people using the module.

2021-03-18 09:15 UTC, martinfalk requested changes
This information needs to be put into the readme.md!
```
netcdf: Require Python 3.9

For reference (in case you cannot upgrade to Python 3.9)
Another solution is to import the typing library in genericnetcdfsource.py:
from typing import List
and replace list[Dimension] with List[Dimension]
```

2021-03-18 10:34 UTC, petersteneteg commented
Typing is a standard package as far as I know, so no installation would be needed. But why not just inte install 3.9 it is backwards compatible

2021-03-18 15:42 UTC, martinfalk approved these changes

2021-03-18 16:34 UTC, merged