feature/molvis
inviwo/modules pull request #174
Opened 2022-02-10 07:51 UTC by martinfalk

some fixes for recent core changes and vtk dataset information

2022-02-14 10:36 UTC, petersteneteg requested changes

2022-02-14 10:36 UTC, petersteneteg commented on misc/vtk/include/inviwo/vtk/processors/vtkdatasetinformation.h
> +            , dataType_(identifier + "dataType", "Data type", array->GetDataTypeAsString())
Why is this inline? why not in the c++? 

Might remove the doc at the top too...

2022-02-14 13:13 UTC, JochenJankowai approved these changes

2022-02-14 13:25 UTC, petersteneteg approved these changes

2022-02-16 18:12 UTC, ResearchDaniel approved these changes

2022-02-17 12:30 UTC, petersteneteg approved these changes

2022-02-23 15:42 UTC, petersteneteg approved these changes

2022-02-24 09:11 UTC, merged