Feature/cpp chgcar
inviwo/modules pull request #230
Opened 2024-06-19 15:39 UTC by petersteneteg

2024-06-20 12:04 UTC, martinfalk requested changes

2024-08-20 12:52 UTC, petersteneteg commented
This will not build without vcpkg...

2024-08-20 14:31 UTC, martinfalk approved these changes

2024-08-22 13:31 UTC, martinfalk approved these changes

2024-08-28 14:35 UTC, martinfalk approved these changes

2024-08-29 09:56 UTC, merged